data = xlsread('Singal-Antenna1-4.csv', 'A:D'); %for temporary use
global global_data_x;
global global_data_y;
global global_data_z;
global global_data_v;
[global_data_x,global_data_y,global_data_z,global_data_v] ...
= interpolation(data);
%surf();
slicedraw(3700,400,300);
xslider = uicontrol('Style', 'slider',...
        'Min',350,'Max',4000,'Value',3700,...
        'Position', [30 5 120 20],...
        'Tag','sliderx','Callback', @xsliderchange); 
yslider = uicontrol('Style', 'slider',...
        'Min',-700,'Max',700,'Value',400,...
        'Position', [215 5 120 20],...
        'Tag','slidery','Callback', @ysliderchange); 
zslider = uicontrol('Style', 'slider',...
        'Min',200,'Max',850,'Value',300,...
        'Position', [400 5 120 20],...
        'Tag','sliderz','Callback', @zsliderchange); 
% initial begin position of xslice, yslice and zslice
xslider.UserData=3700;
yslider.UserData=400;
zslider.UserData=300;
